controllers:
  resource: ../../src/Controller
  type: annotation
  prefix:
    en: '/en'
    fr: '/fr'
  requirements:
    _locale: 'fr|en'
  defaults:
    _locale: 'fr'
kernel:
  resource: ../../src/Kernel.php
  type: annotation